# Generated by Django 6.0.6 on 2026-07-04 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workspacemember',
            name='unique_workspace_user',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='slug',
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='workspacemember',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_member'),
        ),
    ]
