# Generated by Django 6.0.6 on 2026-07-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentversion',
            old_name='created_at',
            new_name='saved_at',
        ),
        migrations.RenameField(
            model_name='documentversion',
            old_name='edited_by',
            new_name='saved_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='content',
            field=models.TextField(),
        ),
    ]
